APPLICATION=first-app-with-thread

BOARD ?= native

USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += ps

RIOTBASE ?= $(CURDIR)/../../../RIOT

DEVELHELP ?= 1

include $(RIOTBASE)/Makefile.include
