APPLICATION=timers

BOARD ?= b-l072z-lrwan1 

USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += ps

RIOTBASE ?= $(CURDIR)/../../../RIOT

DEVELHELP ?= 1

include $(RIOTBASE)/Makefile.include
